global:
  scrape_interval: 15s  # Intervalo entre las consultas a los endpoints

scrape_configs:
  - job_name: 'product-service'  # Nombre del trabajo para el Product Service
  
    static_configs:
      - targets: ["localhost:8080"]
    metrics_path: '/actuator/prometheus'